<a href="https://colab.research.google.com/github/abdullahubaids/Praktikum-Pembelajaran-Mesin/blob/main/Tugas3_PPM_B_1197050002_AbdullahUbaidSalim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# %%
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/Colab Notebooks/PPM/3/DatasetForCoffeeSales2.csv'
data = pd.read_csv(file_path)

# %%
display(data.head(10))
# %%
data.filter(["City", "Category", "Product", "Quantity"]).head()
# %%
data.sort_values("Quantity", axis=0, ascending=False, inplace=True, na_position="last")
display(data.head())
# %%
grp1 = data.groupby('City')
result = grp1['Final Sales'].aggregate('sum')
print(result)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Date,Customer_ID,City,Category,Product,Unit Price,Quantity,Sales Amount,Used_Discount,Discount_Amount,Final Sales
0,1/1/2023,32,Riyadh,coffee beans,Colombian,40,14,560,False,0,560
1,1/2/2023,49,Abha,coffee beans,Costa Rica,35,17,595,False,0,595
2,1/3/2023,75,Tabuk,coffee beans,Costa Rica,35,19,665,False,0,665
3,1/4/2023,80,Abha,coffee beans,Ethiopian,45,1,45,False,0,45
4,1/5/2023,78,Hail,coffee beans,Colombian,40,46,1840,True,368,1472
5,1/6/2023,1,Khobar,coffee beans,Colombian,40,32,1280,True,256,1024
6,1/7/2023,95,Buraidah,coffee beans,Brazilian,30,1,30,True,6,24
7,1/8/2023,27,Medina,coffee beans,Colombian,40,33,1320,False,0,1320
8,1/9/2023,73,Hail,coffee beans,Guatemala,35,47,1645,False,0,1645
9,1/10/2023,82,Dammam,coffee beans,Costa Rica,35,4,140,False,0,140

,Date,Customer_ID,City,Category,Product,Unit Price,Quantity,Sales Amount,Used_Discount,Discount_Amount,Final Sales
15,1/16/2023,36,Jeddah,coffee beans,Ethiopian,45,49,2205,True,441,1764
355,12/22/2023,31,Buraidah,coffee beans,Brazilian,30,49,1470,False,0,1470
577,7/31/2024,65,Dammam,coffee beans,Colombian,40,49,1960,True,392,1568
149,5/30/2023,4,Abha,coffee beans,Costa Rica,35,49,1715,False,0,1715
696,11/27/2024,80,Buraidah,coffee beans,Colombian,40,49,1960,True,392,1568

City
Abha        52831
Buraidah    56875
Dammam      59975
Hail        77257
Jeddah      72048
Khobar      59989
Mecca       66420
Medina      64813
Riyadh      68421
Tabuk       51019
Name: Final Sales, dtype: int64

In [37]:
# %%
import pandas as pd

# %%
# reading the database


file_path = '/content/drive/My Drive/Colab Notebooks/PPM/3/students.csv'
data = pd.read_csv(file_path)

# %%
# printing the top 10 rows
display(data.head(10))

# %%
# Show the dataset info
data.info()

# %%
# Missing Value Checking
data.isna().sum()

# %%
# Filling Nan Value with mode
data.fillna({"lunch": data["lunch"].mode()[0]}, inplace=True)

#%%
# Filling Nan Value with mean
data.fillna({"reading score": data["reading score"].mean()}, inplace=True)

# %%
# Filling Nan Value with mode
data.fillna({"grade": data["grade"].median()}, inplace=True)

# %%
# Check the information of the dataset
data.info()

# %%
# printing the top 10 rows
display(data.head(10))

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,grade
0,female,group B,bachelor's degree,standard,none,72,72.0,74,8.0
1,female,group C,some college,standard,completed,69,90.0,88,7.0
2,female,group B,master's degree,standard,none,90,95.0,93,7.0
3,male,group A,associate's degree,free/reduced,none,47,57.0,44,8.0
4,male,group C,some college,standard,none,76,78.0,75,8.0
5,female,group B,associate's degree,standard,none,71,83.0,78,7.0
6,female,group B,some college,NaN,completed,88,95.0,92,NaN
7,male,group B,some college,free/reduced,none,40,43.0,39,8.0
8,male,group D,high school,free/reduced,completed,64,64.0,67,NaN
9,female,group B,high school,free/reduced,none,38,60.0,50,9.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        975 non-null    object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                976 non-null    float64
 7   writing score                1000 non-null   int64
 8   grade                        985 non-null    float64
dtypes: float64(2), int64(2), object(5)
memory usage: 70.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   float64
 7   writing score                1000 non-null   int64
 8   grade                        1000 non-null   float64
dtypes: float64(2), int64(2), object(5)
memory usage: 70.4+ KB

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,grade
0,female,group B,bachelor's degree,standard,none,72,72.0,74,8.0
1,female,group C,some college,standard,completed,69,90.0,88,7.0
2,female,group B,master's degree,standard,none,90,95.0,93,7.0
3,male,group A,associate's degree,free/reduced,none,47,57.0,44,8.0
4,male,group C,some college,standard,none,76,78.0,75,8.0
5,female,group B,associate's degree,standard,none,71,83.0,78,7.0
6,female,group B,some college,standard,completed,88,95.0,92,8.0
7,male,group B,some college,free/reduced,none,40,43.0,39,8.0
8,male,group D,high school,free/reduced,completed,64,64.0,67,8.0
9,female,group B,high school,free/reduced,none,38,60.0,50,9.0